version: "3.8"

volumes:
  rabbitmq_data:

services:

  #################################
#   Trainer: The trainer microservice
  #################################
  # trainer:
  #   build:
  #     context: ./
  #     dockerfile: trainer.Dockerfile
  #   image:  team01/trainer:esd
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/lms_trainer
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "6800:6800"



  #################################
#   Course: The course Service
  #################################
  course:
    build:
      context: ./
      dockerfile: course.Dockerfile
    image:  team01/course:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/lms_course
      PYTHONUNBUFFERED: 1
    ports:
      - "6900:6900"

#   #################################
# #   Quiz: The quiz Service
#   #################################
#   quiz:
#     build:
#       context: ./
#       dockerfile: quiz.Dockerfile
#     image:  team01/course:esd
#     restart: always
#     environment:
#       dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/lms_course
#       PYTHONUNBUFFERED: 1
#     ports:
#       - "7000:7000"


#   #################################
# #   Class: The class Service
#   #################################
#   class:
#     build:
#       context: ./
#       dockerfile: class.Dockerfile
#     image:  team01/course:esd
#     restart: always
#     environment:
#       dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/lms_course
#       PYTHONUNBUFFERED: 1
#     ports:
#       - "6700:6700"

#   #################################
# #   Lesson: The lesson Service
#   #################################
#   lesson:
#     build:
#       context: ./
#       dockerfile: lesson.Dockerfile
#     image:  team01/course:esd
#     restart: always
#     environment:
#       dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/lms_course
#       PYTHONUNBUFFERED: 1
#     ports:
#       - "6600:6600"